### ISSUE TITLE
how to fix it ? 

### ISSUE THREAD

**Issue by D-Mad** [ddPn08/stable-diffusion-webui-vae-merger#3]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 2515/2515 [00:01<00:00, 1885.50it/s]
Saving ckpt to Stable-diffusion/test1.ckpt
Traceback (most recent call last):
  File "/media/dev_ai/linuxData/anaconda3/envs/SDXL/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/media/dev_ai/linuxData/anaconda3/envs/SDXL/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/media/dev_ai/linuxData/anaconda3/envs/SDXL/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/media/dev_ai/linuxData/anaconda3/envs/SDXL/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/media/dev_ai/linuxData/anaconda3/envs/SDXL/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/media/dev_ai/linuxData/anaconda3/envs/SDXL/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/media/dev_ai/linuxData/anaconda3/envs/SDXL/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/media/dev_ai/linuxData/stable-diffusion-webui/extensions/maji-merger/scripts/maji_merger/tabs/sdxl.py", line 43, in merge_and_save
    merger.save_ckpt(ckpt, fullpath)
  File "/media/dev_ai/linuxData/stable-diffusion-webui/extensions/maji-merger/scripts/maji_merger/merger.py", line 34, in save_ckpt
    else:
  File "/media/dev_ai/linuxData/anaconda3/envs/SDXL/lib/python3.10/site-packages/torch/serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/media/dev_ai/linuxData/anaconda3/envs/SDXL/lib/python3.10/site-packages/torch/serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/media/dev_ai/linuxData/anaconda3/envs/SDXL/lib/python3.10/site-packages/torch/serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory Stable-diffusion does not exist.

**Comment by D-Mad** [comment]
in linux ckpt folder is wrong ?
